--1) Create tables 

CREATE TABLE DEPARTMENTS (
     DEPT_NO VARCHAR(4) NOT NULL,
     DEPT_NAME VARCHAR(40) NOT NULL,
     PRIMARY KEY (DEPT_NO),
     UNIQUE (DEPT_NAME)
);
CREATE TABLE EMPLOYEES (
	EMP_NO INT NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	FIRST_NAME VARCHAR NOT NULL,
	LAST_NAME VARCHAR NOT NULL,
	GENDER VARCHAR NOT NULL,
	HIRE_DATE DATE NOT NULL,
	PRIMARY KEY (EMP_NO)
);
CREATE TABLE DEPT_MANAGER (
	DEPT_NO VARCHAR(4) NOT NULL,
	EMP_NO INT NOT NULL,
	FROM_DATE DATE NOT NULL,
	TO_DATE DATE NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO),
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS (DEPT_NO),
	PRIMARY KEY (EMP_NO, DEPT_NO)
);
CREATE TABLE SALARIES (
	EMP_NO INT NOT NULL,
	SALARY INT NOT NULL,
	FROM_DATE DATE NOT NULL,
	TO_DATE DATE NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO),
	PRIMARY KEY (EMP_NO)
);
CREATE TABLE TITLES (
	EMP_NO INT NOT NULL,
	TITLE VARCHAR(50) NOT NULL,
	FROM_DATE DATE NOT NULL,
	TO_DATE DATE NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO),
	PRIMARY KEY (EMP_NO)
);
CREATE TABLE DEPT_EMP (
	EMP_NO INT NOT NULL,
	DEPT_NO VARCHAR(4) NOT NULL,
	FROM_DATE DATE NOT NULL,
	TO_DATE DATE NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO),
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS (DEPT_NO),
	PRIMARY KEY (EMP_NO, DEPT_NO)
);

-- 2) Create retirement table

SELECT EMP.EMP_NO, EMP.FIRST_NAME, EMP.LAST_NAME, 
	TIT.TITLE, TIT.FROM_DATE, TIT.TO_DATE

INTO RETIREMENT FROM EMPLOYEES AS EMP
INNER JOIN TITLES AS TIT ON EMP.EMP_NO = TIT.EMP_NO
	WHERE (EMP.BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31')
	ORDER BY EMP_NO ASC, TITLE ASC, TO_DATE DESC;

-- Remove duplicate entries & filter based on to_date

SELECT EMP_NO, (SELECT DISTINCT ON (FIRST_NAME) FIRST_NAME), 
	LAST_NAME, TITLE 

INTO RETIREMENT_INFO FROM RETIREMENT 
	WHERE (TO_DATE = '9999-01-01')

-- Retrieve number of employees about to retire by their most recent job

SELECT COUNT(TITLE), TITLE 

INTO RETIREMENT_COUNT FROM RETIREMENT_INFO 
	GROUP BY TITLE 
	ORDER BY COUNT(TITLE) DESC

-- Create mentorship table

SELECT EMP.EMP_NO, EMP.FIRST_NAME, EMP.LAST_NAME, EMP.BIRTH_DATE,
	DEP.FROM_DATE, DEP.TO_DATE, TIT.TITLE

INTO MENTORSHIP FROM EMPLOYEES AS EMP
INNER JOIN DEPT_EMP AS DEP ON EMP.EMP_NO = DEP.EMP_NO
INNER JOIN TITLES AS TIT ON EMP.EMP_NO = TIT.EMP_NO
	WHERE (DEP.TO_DATE = '9999-01-01') AND 
		(EMP.BIRTH_DATE BETWEEN '1965-01-01' AND '1965-12-31')
	ORDER BY EMP_NO ASC, TITLE ASC, TO_DATE DESC ;

-- Remove duplicates

SELECT DISTINCT ON (EMP_NO) EMP_NO, FIRST_NAME, 
    LAST_NAME, BIRTH_DATE, FROM_DATE, TO_DATE, TITLE

INTO MENTORSHIP_INFO FROM MENTORSHIP 

-- Find each departments average age and start year

SELECT T.TITLE AS JOB_TITLE,
	ROUND(AVG(EXTRACT(YEAR FROM E.BIRTH_DATE)),0) AS AVERAGE_BIRTH_DATE,
	ROUND(AVG(EXTRACT(YEAR FROM T.FROM_DATE)),0) AS AVERAGE_EMPLOYEMENT_DATE,
	COUNT(T.TITLE) AS JOB_COUNT
FROM TITLES AS T
INNER JOIN EMPLOYEES AS E ON T.EMP_NO = E.EMP_NO
GROUP BY TITLE;
